- name: Enable Redis module
  command: dnf module enable redis -y

- name: Install Redis
  yum:
    name: redis
    state: present

- name: Update Redis bind address
  replace:
    path: /etc/redis.conf
    regexp: '^bind .*'
    replace: 'bind 0.0.0.0'

- name: Enable and restart Redis
  systemd:
    name: redis
    enabled: yes
    state: restarted