- name: Install Remi repository
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: present

- name: Enable Redis 6.2 module
  command: yum module enable redis:remi-6.2 -y
  args:
    creates: /etc/yum.repos.d/remi.repo

- name: Install Redis
  yum:
    name: redis
    state: present

- name: Update Redis listen address in redis.conf
  replace:
    path: "{{ item }}"
    regexp: '^bind 127\.0\.0\.1'
    replace: 'bind 0.0.0.0'
  loop:
    - /etc/redis.conf
    - /etc/redis/redis.conf

- name: Enable and restart Redis
  systemd:
    name: redis
    enabled: yes
    state: restarted