- name: Install Remi repository manually
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: present
    disable_gpg_check: yes

- name: Enable Redis 6.2 module
  command: dnf module enable redis:remi-6.2 -y

- name: Install Redis
  yum:
    name: redis
    state: present

- name: Update Redis bind address
  replace:
    path: "{{ item }}"
    regexp: '^bind .*'
    replace: 'bind 0.0.0.0'
  loop:
    - /etc/redis.conf
    - /etc/redis/redis.conf

- name: Enable and restart Redis
  systemd:
    name: redis
    enabled: yes
    state: restarted