- name: Install EPEL
  yum:
    name: epel-release
    state: present

- name: Install Remi repo
  yum:
    name: remi-release
    state: present

- name: Enable Redis 6.2 module
  command: dnf module enable redis:remi-6.2 -y

- name: Install Redis
  yum:
    name: redis
    state: present

- name: Update Redis bind address
  replace:
    path: "{{ item }}"
    regexp: '^bind .*'
    replace: 'bind 0.0.0.0'
  loop:
    - /etc/redis.conf
    - /etc/redis/redis.conf
  ignore_errors: yes

- name: Enable and restart Redis
  systemd:
    name: redis
    enabled: yes
    state: restarted