- name: Ensure Nginx is at the latest version
  ansible.builtin.yum:
    name: nginx
    state: latest


- name: Remove old content from /usr/share/nginx/html
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create directory /usr/share/nginx/html
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download and extract frontend
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Update Frontend Configuration
  copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Enable and Start nginx
  service:
    name: nginx
    state: started
    enabled: yes
