- name: Configuring NodeJS Repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed
















# nodejs() {
#   echo -e "${color} Configuring NodeJS Repos ${nocolor}"
#   curl -sL https://rpm.nodesource.com/setup_lts.x | bash  &>>$log_file
#   stat_check $?

#   echo -e "${color} Install NodeJS${nocolor}"
#   yum install nodejs -y  &>>$log_file
#   stat_check $?

#   app_presetup

#   echo -e "${color} Install NodeJS Dependencies${nocolor}"
#   npm install  &>>$log_file
#   stat_check $?

#   systemd_setup
# }