- name: Configuring NodeJS Repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: app pre-requisites
  ansible.builtin.import_tasks:
    file: app_presetup.yml

- name: load nodejs Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Load Schema
  ansible.builtin.import_tasks:
    file: mongo_schema_setup.yml
  when: load_schema

- name: systemd setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml